# Generated by Django 6.0.6 on 2026-07-03 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('salary_min', models.PositiveIntegerField()),
                ('salary_max', models.PositiveIntegerField()),
                ('employment_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='jobs', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs',
                'indexes': [models.Index(fields=['company'], name='idx_jobs_company_id'), models.Index(fields=['location'], name='idx_jobs_location'), models.Index(fields=['employment_type'], name='idx_jobs_employment_type'), models.Index(fields=['status'], name='idx_jobs_status'), models.Index(fields=['salary_min', 'salary_max'], name='idx_jobs_salary_min_salary_max'), models.Index(fields=['status', 'location', 'employment_type'], name='idx_jobs_status_loc_emp'), models.Index(fields=['-created_at'], name='idx_jobs_created_at'), models.Index(fields=['deleted_at'], name='idx_jobs_deleted_at')],
                'constraints': [models.CheckConstraint(condition=models.Q(('salary_max__gte', models.F('salary_min'))), name='chk_jobs_salary_max_greater_or_equal_min')],
            },
        ),
    ]
